services:
  - type: web
    name: zad-compiler-backend
    env: docker
    rootDir: backend
    dockerCommand: npm start
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DOCKER_HOST
        value: unix:///var/run/docker.sock
    disk:
      name: temp
      mountPath: /usr/src/app/temp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
